name: Check US Visa Site

on:
  schedule:
    - cron: "*/5 * * * *"   # runs every 5 minutes
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check site
        run: |
          STATUS=$(curl -s https://www.usvisascheduling.com/)

          if echo "$STATUS" | grep -q "Atlas360-MMode.png"; then
            echo "Site is DOWN (maintenance mode)"
          else
            echo "Site is UP, sending notification"
            curl -X POST https://api.callmebot.com/whatsapp.php?phone=YOURNUMBER&apikey=YOURAPIKEY&text=Visa+Site+Is+UP
          fi
